server {
listen 8082;
listen [::]:8082;
server_name 221.121.4.90;
root /var/www/devops-hackathon-de004-loibd/src;
index index.html;
access_log /var/log/nginx/loibd-k24cntt2.access.log;
error_log /var/log/nginx/loibd-k24cntt2.error.log;
location / {
allow all;
try_files $uri $uri/ =404;
}
}